// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Color: typeof import('./src/components/Color.vue')['default']
    Command: typeof import('./src/components/Command.vue')['default']
    CopyText: typeof import('./src/components/CopyText.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Help: typeof import('./src/components/Help.vue')['default']
    Mark: typeof import('./src/components/Mark.vue')['default']
  }
}

export { }
